'use client'

import React, { useState, useEffect, useRef } from 'react'
import type { Palette } from '@/lib/watercolorPrompt'

interface CeremonyData {
  type: string
  customName?: string
  lieu: string
  adresse: string
  illustrationUrl?: string
}

const GOLD = '#C9A84C'

const BTN: React.CSSProperties = {
  touchAction: 'manipulation',
  WebkitTapHighlightColor: 'transparent',
  cursor: 'pointer',
}

const CEREMONY_LABELS: Record<string, string> = {
  'Mairie': 'Mairie',
  'Cérémonie religieuse / Houppa': 'Houppa',
  'Shabbat Hatan': 'Shabbat Hatan',
  'Henné': 'Henné',
  'Cocktail': 'Cocktail',
  'Soirée': 'Soirée',
  'Boat Party': 'Boat Party',
  'Autre': 'Événement',
}

export default function CeremonyWatercolorPanel({
  ceremonies,
  palette,
  onUpdateCeremony,
}: {
  ceremonies: CeremonyData[]
  palette: Palette
  onUpdateCeremony: (index: number, updates: { illustrationUrl?: string }) => void
}) {
  const [generatingIdx, setGeneratingIdx] = useState<number | null>(null)
  const [candidates, setCandidates] = useState<Record<number, string[]>>({})
  const [savingKey, setSavingKey] = useState<string | null>(null)
  const [error, setError] = useState('')
  const autoGenerated = useRef<Set<number>>(new Set())

  const ceremoniesWithLieu = ceremonies.map((c, i) => ({ ...c, originalIndex: i })).filter(c => c.lieu.trim())

  const generate = async (idx: number, lieu: string, adresse: string, type: string) => {
    setGeneratingIdx(idx)
    setError('')
    setCandidates(prev => ({ ...prev, [idx]: [] }))
    try {
      const res = await fetch('/api/generate-watercolor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode: 'venue', lieu, adresse, ceremonyType: type, palette }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Erreur')
      setCandidates(prev => ({ ...prev, [idx]: data.images }))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Erreur lors de la génération')
    } finally {
      setGeneratingIdx(null)
    }
  }

  // ── Auto-génération au montage pour les cérémonies sans aquarelle ──
  useEffect(() => {
    const toGenerate = ceremoniesWithLieu.filter(c => !c.illustrationUrl && !autoGenerated.current.has(c.originalIndex))
    if (toGenerate.length === 0) return
    // Générer la première cérémonie sans aquarelle
    const first = toGenerate[0]
    autoGenerated.current.add(first.originalIndex)
    generate(first.originalIndex, first.lieu, first.adresse, first.type)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ceremoniesWithLieu.length])

  // Auto-chaîner : quand une génération finit et qu'il reste des cérémonies sans aquarelle
  useEffect(() => {
    if (generatingIdx !== null) return
    const toGenerate = ceremoniesWithLieu.filter(c => !c.illustrationUrl && !candidates[c.originalIndex]?.length && !autoGenerated.current.has(c.originalIndex))
    if (toGenerate.length === 0) return
    const next = toGenerate[0]
    autoGenerated.current.add(next.originalIndex)
    generate(next.originalIndex, next.lieu, next.adresse, next.type)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [generatingIdx])

  const selectImage = async (ceremonyIdx: number, imageUrl: string) => {
    const key = `${ceremonyIdx}-${imageUrl}`
    setSavingKey(key)
    setError('')
    try {
      const res = await fetch('/api/save-watercolor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ imageUrl }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Erreur')
      onUpdateCeremony(ceremonyIdx, { illustrationUrl: data.url })
      setCandidates(prev => {
        const next = { ...prev }
        delete next[ceremonyIdx]
        return next
      })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Erreur lors de la sauvegarde')
    } finally {
      setSavingKey(null)
    }
  }

  if (ceremoniesWithLieu.length === 0) {
    return (
      <p style={{ fontSize: 13, color: '#9a928a', textAlign: 'center', padding: 20, fontStyle: 'italic' }}>
        Renseignez les lieux de vos événements à l&apos;étape 3 pour générer des aquarelles personnalisées.
      </p>
    )
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      {error && (
        <p style={{ color: '#dc2626', fontSize: 13, textAlign: 'center' }}>{error}</p>
      )}

      {ceremoniesWithLieu.map(c => {
        const idx = c.originalIndex
        const label = c.customName || CEREMONY_LABELS[c.type] || c.type
        const isGenerating = generatingIdx === idx
        const imgs = candidates[idx] || []
        const accepted = c.illustrationUrl

        return (
          <div key={idx} style={{ background: '#fdf8f0', borderRadius: 12, padding: 12, border: '1px solid #e8e0d8' }}>
            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
              <div>
                <div style={{ fontSize: 11, color: GOLD, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em' }}>{label}</div>
                <div style={{ fontSize: 12, color: '#3a3330', fontWeight: 600, marginTop: 1 }}>{c.lieu}</div>
              </div>
              {/* Accepted thumbnail compact */}
              {accepted && !imgs.length && (
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={accepted} alt={label} style={{ width: 56, height: 38, objectFit: 'cover', borderRadius: 6, border: '2px solid #7a9e6e' }} />
                  <button
                    type="button"
                    onClick={() => generate(idx, c.lieu, c.adresse, c.type)}
                    disabled={generatingIdx !== null}
                    style={{ ...BTN, background: 'none', border: 'none', color: '#9a928a', fontSize: 10, textDecoration: 'underline', padding: 0 }}
                  >
                    Changer
                  </button>
                </div>
              )}
            </div>

            {/* Generating state */}
            {isGenerating && (
              <div style={{ textAlign: 'center', padding: '14px 0' }}>
                <div style={{ fontFamily: 'var(--font-great-vibes)', fontSize: 18, color: GOLD, marginBottom: 4 }}>
                  L&apos;artiste peint...
                </div>
                <p style={{ fontFamily: 'var(--font-cormorant-garamond)', fontStyle: 'italic', fontSize: 11, color: '#9a928a', margin: 0 }}>
                  Aquarelle de &laquo;&nbsp;{c.lieu}&nbsp;&raquo; en cours
                </p>
              </div>
            )}

            {/* Candidates to choose from */}
            {imgs.length > 0 && !isGenerating && (
              <div>
                <p style={{ fontSize: 11, fontWeight: 600, color: '#3a3330', marginBottom: 6, textAlign: 'center' }}>
                  Choisissez votre préférée
                </p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 8 }}>
                  {imgs.map((url, i) => {
                    const saving = savingKey === `${idx}-${url}`
                    return (
                      <button
                        key={i}
                        type="button"
                        onClick={() => selectImage(idx, url)}
                        disabled={savingKey !== null}
                        style={{
                          ...BTN, padding: 0, border: `2px solid ${saving ? GOLD : 'transparent'}`,
                          borderRadius: 8, overflow: 'hidden', position: 'relative',
                          opacity: savingKey !== null && !saving ? 0.5 : 1,
                        }}
                      >
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={url} alt={`Option ${i + 1}`} style={{ width: '100%', aspectRatio: '3/2', objectFit: 'cover', display: 'block' }} />
                        {saving && (
                          <div style={{ position: 'absolute', inset: 0, background: 'rgba(255,255,255,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                            <span style={{ fontSize: 11, color: GOLD, fontWeight: 700 }}>...</span>
                          </div>
                        )}
                        <div style={{ position: 'absolute', bottom: 4, left: '50%', transform: 'translateX(-50%)', background: 'rgba(255,255,255,0.9)', borderRadius: 9999, padding: '2px 10px', fontSize: 9, fontWeight: 600, color: GOLD }}>
                          Choisir
                        </div>
                      </button>
                    )
                  })}
                </div>
                <button
                  type="button"
                  onClick={() => generate(idx, c.lieu, c.adresse, c.type)}
                  disabled={generatingIdx !== null}
                  style={{ ...BTN, display: 'block', margin: '8px auto 0', background: 'none', border: 'none', color: '#9a928a', fontSize: 10, textDecoration: 'underline' }}
                >
                  Régénérer
                </button>
              </div>
            )}

            {/* Initial state: auto-generation pending (no button needed) */}
            {!accepted && !imgs.length && !isGenerating && (
              <div style={{ textAlign: 'center', padding: '8px 0' }}>
                <div style={{ fontSize: 11, color: '#9a928a', fontStyle: 'italic' }}>En attente de génération…</div>
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}
